# Generated by Django 5.2.7 on 2026-04-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('analyst', 'Analyst'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
