from .models import ROLE_ADMIN, ROLE_HR, ROLE_ANALYST, ROLE_USER

ROLE_ASSIGNMENT_RULES = {
    ROLE_ADMIN: [ROLE_HR, ROLE_ANALYST, ROLE_USER],
    ROLE_HR: [ROLE_ANALYST, ROLE_USER],
}

ALL_ROLES = [ROLE_ADMIN, ROLE_HR, ROLE_ANALYST, ROLE_USER]